# Starter pipeline azure
trigger:
  - test/* # Generates an alpha codename version (because it's very imbryonic)
  - develop # Generates a beta codename (closer to release)
  - master # Official release
  - hotfix/* # Official release
  
variables:
  - group: release-note-auth
  - group: terraform-ci

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:

  - template: stages/bootstrap3.yml@templates

  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'Ubuntu-20.04'

        steps:
        - task: GitHubRelease@1
          displayName: PushRelease
          inputs:
            gitHubConnection: 'guifabmello-access-token'
            repositoryName: 'guifabmello/terraform-helm-release'
            title: $(Build.BuildNumber)
            action: 'create'
            tagSource: manual
            tag: $(Build.BuildNumber)
            addChangeLog: true
            assets: |
              $(Build.ArtifactStagingDirectory)/README.md
              $(Build.ArtifactStagingDirectory)/CHANGELOG.md