# Starter pipeline azure
trigger:
  - test/* # Generates an alpha codename version (because it's very imbryonic)
  - develop # Generates a beta codename (closer to release)
  - master # Official release
  - hotfix/* # Official release
  
variables:
  - group: release-note-auth
  - group: terraform-ci

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:

  - template: stages/bootstrap3.yml@templates

  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'Ubuntu-20.04'

        steps:
        - task: Bash@3
          inputs:
          targetType: 'inline'
          script: |
            echo Repository name: $(Build.Repository.Name)

        - task: GitHubRelease@0
          displayName: PushRelease
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
          inputs:
            gitHubConnection: 'guifabmello-access-token'
            repositoryName: $(Build.Repository.Name)
            title: $(Build.BuildNumber)
            action: 'create'
            tagSource: manual
            tags: |
              latest
              $(Build.BuildNumber)
            addChangeLog: true
            assets: |
              $(Build.ArtifactStagingDirectory)/README.md
              $(Build.ArtifactStagingDirectory)/CHANGELOG.md
